# Variables
CC = $(CROSS_COMPILE)gcc
CFLAGS = -Wall -Wextra -o2 -g

writer: writer.c
	$(CC) $(CFLAG) -o writer  writer.c

writer.c:
	echo "writer.c not found"

.PHONY: clean
clean:
	rm -f writer *.o


